FIX: All payment types returned on GET/paymenttypes
nss-day-cohort-48/bangazon-DakotaLambert pull request #28
Opened 2021-09-01 16:41 UTC by DakotaLambert

## Changes

- Profile view
> Added payment serializer to return the current users payment types (not all information)

- PaymentTypes 
> Changed LIST to get customer by auth.user, to return the payment types of the current user.

## Requests / Responses

**Request**

GET `/profile`

**Response**

```json
{
    "id": 5,
    "url": "http://localhost:8000/customers/5",
    "user": {
        "first_name": "Joe",
        "last_name": "Shepherd",
        "email": "joe@joeshepherd.com"
    },
    "phone_number": "555-1212",
    "address": "100 Endless Way",
    "payment_types": [
        {
            "merchant_name": "Visa",
            "customer": {
                "id": 5,
                "user": {
                    "first_name": "Joe",
                    "last_name": "Shepherd",
                    "email": "joe@joeshepherd.com"
                }
            },
            "expiration_date": "2020-01-01"
        }
    ],
    "recommends": []
}
```
**Request**

GET `/paymenttypes`

**Response**

```json
[
    {
        "id": 1,
        "url": "http://localhost:8000/paymenttypes/1",
        "merchant_name": "Visa",
        "account_number": "24ijio68948fj8439",
        "expiration_date": "2020-01-01",
        "create_date": "2019-11-11",
        "customer_id": 5
    }
]
```

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database
- [ ] Open PostMan
- [ ] GET http://localhost:8000/paymenttypes
- [ ] Refer to /paymenttypes response
- [ ] GET http://localhost:8000/profile
- [ ] Refer to /profile response

## Related Issues

- Fixes #18

2021-09-01 17:31 UTC, heymonicakay requested changes
Nice work! Issue #18 is linked in the PR description, but the code includes changes that fix issue #19 as also. Please revise your PR description to link all related issues. Ping me when that's done, and you'll be good to go!

2021-09-01 17:31 UTC, heymonicakay commented on bangazonapi/views/paymenttype.py
> +        new_payment.expiration_date = request.data["expiration_date"]
Fixes #19

2021-09-01 19:02 UTC, DakotaLambert commented on bangazonapi/views/paymenttype.py
> +        new_payment.expiration_date = request.data["expiration_date"]
Edited!

2021-09-02 17:02 UTC, heymonicakay approved these changes

2021-09-02 17:03 UTC, heymonicakay commented
@DakotaLambert Thanks! Approved!

2021-09-02 20:41 UTC, merged