Dl delete
nss-day-cohort-48/bangazon-DakotaLambert pull request #29
Opened 2021-09-01 19:43 UTC by DakotaLambert

Description of PR that completes issue here...

## Changes

-Custom @action in Profile views, added  .delete method.

## Requests / Responses

**Request**

DELETE `/lineitems/4` deletes a lineitem from the /cart url

**Response**

HTTP/1.1 204 NO_CONTENT

```json
{}
```

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database
- [ ] Run PostMan
- [ ] DELETE `http://localhost:8000/lineitems/4`
- [ ] GET `http://localhost:8000/cart`, see if lineitem.id = 4 is there.

## Related Issues

- Fixes #20

2021-09-01 20:24 UTC, gwynnemeeks approved these changes
approved!

2021-09-02 03:13 UTC, heymonicakay requested changes
Requested changes! See my comments for details.

2021-09-02 03:13 UTC, heymonicakay commented on bangazonapi/views/profile.py
> +                open_order = Order.objects.all(
This query is improperly constructed, which results in the following TypeError whenever a`DELETE` request is sent to `/profile/cart`:
```
all() got an unexpected keyword argument 'customer'
```
The `all()` method does not accept any arguments, but it's being passed _two_ positional arguments in your query here. You should only use `all()` to get _all_ data from a given db table. The `filter()` and `get()` methods can be used to retrieve a subset or a single row of matching data respectively. 

You need to modify your query so that it uses the appropriate method correctly. [See Django docs on queries for more info. ](https://docs.djangoproject.com/en/3.2/topics/db/queries/#retrieving-objects)

2021-09-02 03:13 UTC, heymonicakay commented on bangazonapi/views/profile.py
> +from django.db.models import fields
This import should be removed since it's not being used.

2021-09-02 19:04 UTC, gwynnemeeks approved these changes
Monica's changes implemented! Good job! approved

2021-09-02 20:41 UTC, merged